In [12]:
import boto3
import json
import numpy as np
import pandas as pd

In [2]:
s3 = boto3.client('s3')

In [14]:
response = s3.list_objects_v2(Bucket="is459-project-data", Prefix="skytrax/top_100/")
files = [obj['Key'] for obj in response.get('Contents', []) if obj['Key'].endswith('.json')]
all_data = []

for file_key in files:
    obj = s3.get_object(Bucket="is459-project-data", Key=file_key)
    json_content = obj['Body'].read().decode('utf-8')
    
    data = json.loads(json_content)
    all_data.extend(data)

all_data

[[2012, 1, 'Qatar Airways'],
 [2012, 2, 'Asiana Airlines'],
 [2012, 3, 'Singapore Airlines'],
 [2012, 4, 'Cathay Pacific Airways'],
 [2012, 5, 'ANA All Nippon Airways'],
 [2012, 6, 'Etihad Airways'],
 [2012, 7, 'Turkish Airlines'],
 [2012, 8, 'Emirates'],
 [2012, 9, 'Thai Airways'],
 [2012, 10, 'Malaysia Airlines'],
 [2012, 11, 'Garuda Indonesia'],
 [2012, 12, 'Virgin Australia'],
 [2012, 13, 'EVA Air'],
 [2012, 14, 'Lufthansa'],
 [2012, 15, 'Qantas Airways'],
 [2012, 16, 'Korean Air'],
 [2012, 17, 'Air New Zealand'],
 [2012, 18, 'Swiss International Air Lines'],
 [2012, 19, 'Air Canada'],
 [2012, 20, 'Hainan Airlines'],
 [2012, 21, 'Dragonair'],
 [2012, 22, 'AirAsia'],
 [2012, 23, 'Oman Air'],
 [2012, 24, 'Aegean Airlines'],
 [2012, 25, 'South African Airways'],
 [2012, 26, 'Virgin America'],
 [2012, 27, 'Bangkok Airways'],
 [2012, 28, 'British Airways'],
 [2012, 29, 'China Southern Airlines'],
 [2012, 30, 'Jetstar Airways'],
 [2012, 31, 'Finnair'],
 [2012, 32, 'TAM Airlines'],
 [2012, 33, 'China Airlines'],
 [2012, 34, 'KLM Royal Dutch Airlines'],
 [2012, 35, 'Japan Airlines'],
 [2012, 36, 'SilkAir'],
 [2012, 37, 'Air China'],
 [2012, 38, 'LAN Airlines'],
 [2012, 39, 'Austrian Airlines'],
 [2012, 40, 'AirAsia X'],
 [2012, 41, 'EasyJet'],
 [2012, 42, 'TACA Airlines'],
 [2012, 43, 'WestJet'],
 [2012, 44, 'China Eastern Airlines'],
 [2012, 45, 'Hong Kong Airlines'],
 [2012, 46, 'Jetstar Asia'],
 [2012, 47, 'Vietnam Airlines'],
 [2012, 48, 'Air France'],
 [2012, 49, 'Alaska Airlines'],
 [2012, 50, 'Virgin Atlantic'],
 [2012, 51, 'Southwest Airlines'],
 [2012, 52, 'jetBlue Airways'],
 [2012, 53, 'Air Astana'],
 [2012, 54, 'Azul Airlines'],
 [2012, 55, 'IndiGo'],
 [2012, 56, 'Avianca'],
 [2012, 57, 'Delta Air Lines'],
 [2012, 58, 'Jet Airways'],
 [2012, 59, 'bmi British Midland'],
 [2012, 60, 'American Eagle'],
 [2012, 61, 'Copa Airlines'],
 [2012, 62, 'Air Nostrum'],
 [2012, 63, 'Brussels Airlines'],
 [2012, 64, 'United Airlines'],
 [2012, 65, 'Air Berlin'],
 [2012, 66, 'Kulula'],
 [2012, 67, 'TAP Portugal'],
 [2012, 68, 'SAS Scandinavian'],
 [2012, 69, 'TRIP Airlines'],
 [2012, 70, 'SriLankan Airlines'],
 [2012, 71, 'Air Mauritius'],
 [2012, 72, 'Transaero Airlines'],
 [2012, 73, 'Baboo Airlines'],
 [2012, 74, 'Norwegian'],
 [2012, 75, 'NIKI'],
 [2012, 76, 'Air Transat'],
 [2012, 77, 'Hong Kong Express'],
 [2012, 78, 'Kenya Airways'],
 [2012, 79, 'Kingfisher Airlines'],
 [2012, 80, 'Hawaiian Airlines'],
 [2012, 81, 'SpiceJet'],
 [2012, 82, 'Gulf Air'],
 [2012, 83, 'Alitalia'],
 [2012, 84, 'American Airlines'],
 [2012, 85, 'Aeroflot'],
 [2012, 86, 'Tigerair'],
 [2012, 87, 'Saudia'],
 [2012, 88, 'Icelandair'],
 [2012, 89, 'Shenzhen Airlines'],
 [2012, 90, 'Porter Airlines'],
 [2012, 91, 'Aer Arann'],
 [2012, 92, 'Tianjin Airlines'],
 [2012, 93, 'Nok Air'],
 [2012, 94, 'Royal Jordanian Airlines'],
 [2012, 95, 'Egyptair'],
 [2012, 96, 'Air Pacific'],
 [2012, 97, 'Aer Lingus'],
 [2012, 98, 'Aer Busan'],
 [2012, 99, 'Cyprus Airways'],
 [2012, 100, 'Skymark Airlines'],
 [2013, 1, 'Emirates'],
 [2013, 2, 'Qatar Airways'],
 [2013, 3, 'Singapore Airlines'],
 [2013, 4, 'ANA All Nippon Airways'],
 [2013, 5, 'Asiana Airlines'],
 [2013, 6, 'Cathay Pacific Airways'],
 [2013, 7, 'Etihad Airways'],
 [2013, 8, 'Garuda Indonesia'],
 [2013, 9, 'Turkish Airlines'],
 [2013, 10, 'Qantas Airways'],
 [2013, 11, 'Lufthansa'],
 [2013, 12, 'EVA Air'],
 [2013, 13, 'Virgin Australia'],
 [2013, 14, 'Malaysia Airlines'],
 [2013, 15, 'Thai Airways'],
 [2013, 16, 'Swiss International Air Lines'],
 [2013, 17, 'Korean Air'],
 [2013, 18, 'Air New Zealand'],
 [2013, 19, 'Hainan Airlines'],
 [2013, 20, 'Air Canada'],
 [2013, 21, 'South African Airways'],
 [2013, 22, 'Oman Air'],
 [2013, 23, 'Dragonair'],
 [2013, 24, 'AirAsia'],
 [2013, 25, 'Japan Airlines'],
 [2013, 26, 'Jetstar Airways'],
 [2013, 27, 'British Airways'],
 [2013, 28, 'China Southern Airlines'],
 [2013, 29, 'Virgin America'],
 [2013, 30, 'Aegean Airlines'],
 [2013, 31, 'Bangkok Airways'],
 [2013, 32, 'AirAsia X'],
 [2013, 33, 'Austrian Airlines'],
 [2013, 34, 'Finnair'],
 [2013, 35, 'SilkAir'],
 [2013, 36, 'LAN Airlines'],
 [2013, 37, 'KLM Royal Dutch Airlines'],
 [2013, 38, 'Virgin Atlantic'],
 [2013, 39, 'TAM Airlines'],
 [2013, 40, 'Air France'],
 [2013, 41, 'Hong Kong Airlines'],
 [2013, 42, 'Air Astana'],
 [2013, 43, 'IndiGo'],
 [2013, 44, 'Norwegian'],
 [2013, 45, 'Delta Air Lines'],
 [2013, 46, 'jetBlue Airways'],
 [2013, 47, 'Brussels Airlines'],
 [2013, 48, 'Jetstar Asia'],
 [2013, 49, 'EasyJet'],
 [2013, 50, 'China Airlines'],
 [2013, 51, 'Air China'],
 [2013, 52, 'Jet Airways'],
 [2013, 53, 'Vietnam Airlines'],
 [2013, 54, 'SAS Scandinavian'],
 [2013, 55, 'Copa Airlines'],
 [2013, 56, 'Air Seychelles'],
 [2013, 57, 'United Airlines'],
 [2013, 58, 'TACA Airlines'],
 [2013, 59, 'Air Berlin'],
 [2013, 60, 'Shenzhen Airlines'],
 [2013, 61, 'Aeroflot'],
 [2013, 62, 'Alaska Airlines'],
 [2013, 63, 'WestJet'],
 [2013, 64, 'Avianca'],
 [2013, 65, 'Transaero Airlines'],
 [2013, 66, 'China Eastern Airlines'],
 [2013, 67, 'Azul Airlines'],
 [2013, 68, 'SriLankan Airlines'],
 [2013, 69, 'Azerbaijan Airlines'],
 [2013, 70, 'Alitalia'],
 [2013, 71, 'Scoot'],
 [2013, 72, 'Air Mauritius'],
 [2013, 73, 'Icelandair'],
 [2013, 74, 'Southwest Airlines'],
 [2013, 75, 'Aer Lingus'],
 [2013, 76, 'Kulula'],
 [2013, 77, 'TAP Portugal'],
 [2013, 78, 'Air Nostrum'],
 [2013, 79, 'Hawaiian Airlines'],
 [2013, 80, 'Thomson Airways'],
 [2013, 81, 'American Airlines'],
 [2013, 82, 'Tianjin Airlines'],
 [2013, 83, 'SpiceJet'],
 [2013, 84, 'American Eagle'],
 [2013, 85, 'Ethiopian Airlines'],
 [2013, 86, 'Air Transat'],
 [2013, 87, 'Tigerair'],
 [2013, 88, 'Porter Airlines'],
 [2013, 89, 'Peach'],
 [2013, 90, 'Philippine Airlines'],
 [2013, 91, 'Germanwings'],
 [2013, 92, 'Iberia'],
 [2013, 93, 'Kenya Airways'],
 [2013, 94, 'S7 Airlines'],
 [2013, 95, 'Air Pacific'],
 [2013, 96, 'Gulf Air'],
 [2013, 97, 'US Airways'],
 [2013, 98, 'NIKI'],
 [2013, 99, 'Vueling Airlines'],
 [2013, 100, 'Royal Jordanian Airlines'],
 [2014, 1, 'Cathay Pacific Airways'],
 [2014, 2, 'Qatar Airways'],
 [2014, 3, 'Singapore Airlines'],
 [2014, 4, 'Emirates'],
 [2014, 5, 'Turkish Airlines'],
 [2014, 6, 'ANA All Nippon Airways'],
 [2014, 7, 'Garuda Indonesia'],
 [2014, 8, 'Asiana Airlines'],
 [2014, 9, 'Etihad Airways'],
 [2014, 10, 'Lufthansa'],
 [2014, 11, 'Qantas Airways'],
 [2014, 12, 'EVA Air'],
 [2014, 13, 'Swiss International Air Lines'],
 [2014, 14, 'Thai Airways'],
 [2014, 15, 'Virgin Australia'],
 [2014, 16, 'Air New Zealand'],
 [2014, 17, 'British Airways'],
 [2014, 18, 'Malaysia Airlines'],
 [2014, 19, 'Hainan Airlines'],
 [2014, 20, 'Bangkok Airways'],
 [2014, 21, 'Austrian Airlines'],
 [2014, 22, 'South African Airways'],
 [2014, 23, 'Japan Airlines'],
 [2014, 24, 'Air Canada'],
 [2014, 25, 'Air France'],
 [2014, 26, 'Korean Air'],
 [2014, 27, 'Oman Air'],
 [2014, 28, 'Dragonair'],
 [2014, 29, 'Hong Kong Airlines'],
 [2014, 30, 'Aegean Airlines'],
 [2014, 31, 'AirAsia'],
 [2014, 32, 'KLM Royal Dutch Airlines'],
 [2014, 33, 'LAN Airlines'],
 [2014, 34, 'Virgin Atlantic'],
 [2014, 35, 'China Southern Airlines'],
 [2014, 36, 'AirAsia X'],
 [2014, 37, 'Finnair'],
 [2014, 38, 'Norwegian'],
 [2014, 39, 'Jetstar Airways'],
 [2014, 40, 'SilkAir'],
 [2014, 41, 'Air Astana'],
 [2014, 42, 'TAM Airlines'],
 [2014, 43, 'IndiGo'],
 [2014, 44, 'EasyJet'],
 [2014, 45, 'WestJet'],
 [2014, 46, 'Virgin America'],
 [2014, 47, 'Avianca'],
 [2014, 48, 'Brussels Airlines'],
 [2014, 49, 'Delta Air Lines'],
 [2014, 50, 'Jetstar Asia'],
 [2014, 51, 'Aeroflot'],
 [2014, 52, 'SAS Scandinavian'],
 [2014, 53, 'United Airlines'],
 [2014, 54, 'China Airlines'],
 [2014, 55, 'Porter Airlines'],
 [2014, 56, 'Transaero Airlines'],
 [2014, 57, 'Copa Airlines'],
 [2014, 58, 'Vietnam Airlines'],
 [2014, 59, 'jetBlue Airways'],
 [2014, 60, 'Air Mauritius'],
 [2014, 61, 'Scoot'],
 [2014, 62, 'Air Seychelles'],
 [2014, 63, 'Azul Airlines'],
 [2014, 64, 'TAP Portugal'],
 [2014, 65, 'Aer Lingus'],
 [2014, 66, 'Tianjin Airlines'],
 [2014, 67, 'Iberia'],
 [2014, 68, 'Thomson Airways'],
 [2014, 69, 'Alaska Airlines'],
 [2014, 70, 'Air Berlin'],
 [2014, 71, 'Southwest Airlines'],
 [2014, 72, 'Azerbaijan Airlines'],
 [2014, 73, 'SriLankan Airlines'],
 [2014, 74, 'Ethiopian Airlines'],
 [2014, 75, 'Jet Airways'],
 [2014, 76, 'Alitalia'],
 [2014, 77, 'Saudia'],
 [2014, 78, 'Shenzhen Airlines'],
 [2014, 79, 'American Eagle'],
 [2014, 80, 'Peach'],
 [2014, 81, 'Icelandair'],
 [2014, 82, 'Germanwings'],
 [2014, 83, 'Air Nostrum'],
 [2014, 84, 'Kenya Airways'],
 [2014, 85, 'Air China'],
 [2014, 86, 'Gulf Air'],
 [2014, 87, 'SpiceJet'],
 [2014, 88, 'Hawaiian Airlines'],
 [2014, 89, 'American Airlines'],
 [2014, 90, 'Air Transat'],
 [2014, 91, 'Tigerair'],
 [2014, 92, 'TAAG Angola Airlines'],
 [2014, 93, 'Philippine Airlines'],
 [2014, 94, 'China Eastern Airlines'],
 [2014, 95, 'Mango'],
 [2014, 96, 'Vueling Airlines'],
 [2014, 97, 'Fiji Airways'],
 [2014, 98, 'S7 Airlines'],
 [2014, 99, 'Croatia Airlines'],
 [2014, 100, 'Kulula'],
 [2015, 1, 'Qatar Airways'],
 [2015, 2, 'Singapore Airlines'],
 [2015, 3, 'Cathay Pacific Airways'],
 [2015, 4, 'Turkish Airlines'],
 [2015, 5, 'Emirates'],
 [2015, 6, 'Etihad Airways'],
 [2015, 7, 'ANA All Nippon Airways'],
 [2015, 8, 'Garuda Indonesia'],
 [2015, 9, 'EVA Air'],
 [2015, 10, 'Qantas Airways'],
 [2015, 11, 'Asiana Airlines'],
 [2015, 12, 'Lufthansa'],
 [2015, 13, 'Austrian Airlines'],
 [2015, 14, 'Swiss International Air Lines'],
 [2015, 15, 'Air France'],
 [2015, 16, 'Virgin Australia'],
 [2015, 17, 'Air New Zealand'],
 [2015, 18, 'Dragonair'],
 [2015, 19, 'Thai Airways'],
 [2015, 20, 'British Airways'],
 [2015, 21, 'Japan Airlines'],
 [2015, 22, 'Hainan Airlines'],
 [2015, 23, 'Bangkok Airways'],
 [2015, 24, 'Malaysia Airlines'],
 [2015, 25, 'AirAsia'],
 [2015, 26, 'Virgin America'],
 [2015, 27, 'Air Canada'],
 [2015, 28, 'KLM Royal Dutch Airlines'],
 [2015, 29, 'Aegean Airlines'],
 [2015, 30, 'Hong Kong Airlines'],
 [2015, 31, 'Finnair'],
 [2015, 32, 'LAN Airlines'],
 [2015, 33, 'Norwegian'],
 [2015, 34, 'South African Airways'],
 [2015, 35, 'Oman Air'],
 [2015, 36, 'China Southern Airlines'],
 [2015, 37, 'Virgin Atlantic'],
 [2015, 38, 'Korean Air'],
 [2015, 39, 'EasyJet'],
 [2015, 40, 'Air Astana'],
 [2015, 41, 'Jetstar Airways'],
 [2015, 42, 'SilkAir'],
 [2015, 43, 'AirAsia X'],
 [2015, 44, 'IndiGo'],
 [2015, 45, 'Delta Air Lines'],
 [2015, 46, 'Aeroflot'],
 [2015, 47, 'WestJet'],
 [2015, 48, 'Porter Airlines'],
 [2015, 49, 'Avianca'],
 [2015, 50, 'jetBlue Airways'],
 [2015, 51, 'TAM Airlines'],
 [2015, 52, 'China Airlines'],
 [2015, 53, 'Jetstar Asia'],
 [2015, 54, 'Brussels Airlines'],
 [2015, 55, 'Vietnam Airlines'],
 [2015, 56, 'Iberia'],
 [2015, 57, 'SAS Scandinavian'],
 [2015, 58, 'Scoot'],
 [2015, 59, 'Thomson Airways'],
 [2015, 60, 'United Airlines'],
 [2015, 61, 'Aer Lingus'],
 [2015, 62, 'Azul Airlines'],
 [2015, 63, 'Air Seychelles'],
 [2015, 64, 'Copa Airlines'],
 [2015, 65, 'Alaska Airlines'],
 [2015, 66, 'Azerbaijan Airlines'],
 [2015, 67, 'Southwest Airlines'],
 [2015, 68, 'Transaero Airlines'],
 [2015, 69, 'Air Mauritius'],
 [2015, 70, 'TAP Portugal'],
 [2015, 71, 'Air Berlin'],
 [2015, 72, 'Germanwings'],
 [2015, 73, 'SriLankan Airlines'],
 [2015, 74, 'Alitalia'],
 [2015, 75, 'Peach'],
 [2015, 76, 'Jet Airways'],
 [2015, 77, 'Ethiopian Airlines'],
 [2015, 78, 'American Eagle'],
 [2015, 79, 'American Airlines'],
 [2015, 80, 'Air Transat'],
 [2015, 81, 'Icelandair'],
 [2015, 82, 'Hawaiian Airlines'],
 [2015, 83, 'Air Nostrum'],
 [2015, 84, 'Saudia'],
 [2015, 85, 'China Eastern Airlines'],
 [2015, 86, 'Kenya Airways'],
 [2015, 87, 'Philippine Airlines'],
 [2015, 88, 'Gulf Air'],
 [2015, 89, 'Juneyao Air'],
 [2015, 90, 'TAAG Angola Airlines'],
 [2015, 91, 'Tianjin Airlines'],
 [2015, 92, 'Shenzhen Airlines'],
 [2015, 93, 'Air China'],
 [2015, 94, 'SpiceJet'],
 [2015, 95, 'Tigerair'],
 [2015, 96, 'Mango'],
 [2015, 97, 'Vueling Airlines'],
 [2015, 98, 'NIKI'],
 [2015, 99, 'Kulula'],
 [2015, 100, 'Fiji Airways'],
 [2016, 1, 'Emirates'],
 [2016, 2, 'Qatar Airways'],
 [2016, 3, 'Singapore Airlines'],
 [2016, 4, 'Cathay Pacific Airways'],
 [2016, 5, 'ANA All Nippon Airways'],
 [2016, 6, 'Etihad Airways'],
 [2016, 7, 'Turkish Airlines'],
 [2016, 8, 'EVA Air'],
 [2016, 9, 'Qantas Airways'],
 [2016, 10, 'Lufthansa'],
 [2016, 11, 'Garuda Indonesia'],
 [2016, 12, 'Hainan Airlines'],
 [2016, 13, 'Thai Airways'],
 [2016, 14, 'Air France'],
 [2016, 15, 'Swiss International Air Lines'],
 [2016, 16, 'Asiana Airlines'],
 [2016, 17, 'Air New Zealand'],
 [2016, 18, 'Virgin Australia'],
 [2016, 19, 'Austrian Airlines'],
 [2016, 20, 'Bangkok Airways'],
 [2016, 21, 'Japan Airlines'],
 [2016, 22, 'Dragonair'],
 [2016, 23, 'AirAsia'],
 [2016, 24, 'KLM Royal Dutch Airlines'],
 [2016, 25, 'Virgin America'],
 [2016, 26, 'British Airways'],
 [2016, 27, 'Finnair'],
 [2016, 28, 'Virgin Atlantic'],
 [2016, 29, 'Hong Kong Airlines'],
 [2016, 30, 'Norwegian'],
 [2016, 31, 'Air Canada'],
 [2016, 32, 'China Southern Airlines'],
 [2016, 33, 'Aegean Airlines'],
 [2016, 34, 'Malaysia Airlines'],
 [2016, 35, 'Delta Air Lines'],
 [2016, 36, 'Korean Air'],
 [2016, 37, 'China Airlines'],
 [2016, 38, 'EasyJet'],
 [2016, 39, 'SilkAir'],
 [2016, 40, 'Aeroflot'],
 [2016, 41, 'South African Airways'],
 [2016, 42, 'Oman Air'],
 [2016, 43, 'Air Astana'],
 [2016, 44, 'Vietnam Airlines'],
 [2016, 45, 'LAN Airlines'],
 [2016, 46, 'Jetstar Airways'],
 [2016, 47, 'Porter Airlines'],
 [2016, 48, 'AirAsia X'],
 [2016, 49, 'Aer Lingus'],
 [2016, 50, 'WestJet'],
 [2016, 51, 'IndiGo'],
 [2016, 52, 'Iberia'],
 [2016, 53, 'jetBlue Airways'],
 [2016, 54, 'Jetstar Asia'],
 [2016, 55, 'Azul Airlines'],
 [2016, 56, 'Avianca'],
 [2016, 57, 'TAM Airlines'],
 [2016, 58, 'Alitalia'],
 [2016, 59, 'Brussels Airlines'],
 [2016, 60, 'Alaska Airlines'],
 [2016, 61, 'Scoot'],
 [2016, 62, 'SAS Scandinavian'],
 [2016, 63, 'Air Seychelles'],
 [2016, 64, 'TAP Portugal'],
 [2016, 65, 'Thomson Airways'],
 [2016, 66, 'Southwest Airlines'],
 [2016, 67, 'SriLankan Airlines'],
 [2016, 68, 'United Airlines'],
 [2016, 69, 'Copa Airlines'],
 [2016, 70, 'Azerbaijan Airlines'],
 [2016, 71, 'Jet Airways'],
 [2016, 72, 'Hawaiian Airlines'],
 [2016, 73, 'Air Mauritius'],
 [2016, 74, 'Air Berlin'],
 [2016, 75, 'Eurowings'],
 [2016, 76, 'Ethiopian Airlines'],
 [2016, 77, 'American Airlines'],
 [2016, 78, 'Peach'],
 [2016, 79, 'China Eastern Airlines'],
 [2016, 80, 'Gulf Air'],
 [2016, 81, 'Icelandair'],
 [2016, 82, 'Saudia'],
 [2016, 83, 'Philippine Airlines'],
 [2016, 84, 'American Eagle'],
 [2016, 85, 'Kenya Airways'],
 [2016, 86, 'TAAG Angola Airlines'],
 [2016, 87, 'Air China'],
 [2016, 88, 'Air Transat'],
 [2016, 89, 'Air Nostrum'],
 [2016, 90, 'Juneyao Air'],
 [2016, 91, 'Fiji Airways'],
 [2016, 92, 'LOT Polish'],
 [2016, 93, 'Kulula'],
 [2016, 94, 'Aeromexico'],
 [2016, 95, 'Royal Brunei Airlines'],
 [2016, 96, 'Tianjin Airlines'],
 [2016, 97, 'Tigerair'],
 [2016, 98, 'Mango'],
 [2016, 99, 'Royal Jordanian Airlines'],
 [2016, 100, 'SpiceJet'],
 [2017, 1, 'Qatar Airways'],
 [2017, 2, 'Singapore Airlines'],
 [2017, 3, 'ANA All Nippon Airways'],
 [2017, 4, 'Emirates'],
 [2017, 5, 'Cathay Pacific Airways'],
 [2017, 6, 'EVA Air'],
 [2017, 7, 'Lufthansa'],
 [2017, 8, 'Etihad Airways'],
 [2017, 9, 'Hainan Airlines'],
 [2017, 10, 'Garuda Indonesia'],
 [2017, 11, 'Thai Airways'],
 [2017, 12, 'Turkish Airlines'],
 [2017, 13, 'Virgin Australia'],
 [2017, 14, 'Swiss International Air Lines'],
 [2017, 15, 'Qantas Airways'],
 [2017, 16, 'Japan Airlines'],
 [2017, 17, 'Austrian Airlines'],
 [2017, 18, 'Air France'],
 [2017, 19, 'Air New Zealand'],
 [2017, 20, 'Asiana Airlines'],
 [2017, 21, 'Bangkok Airways'],
 [2017, 22, 'KLM Royal Dutch Airlines'],
 [2017, 23, 'China Southern Airlines'],
 [2017, 24, 'Hong Kong Airlines'],
 [2017, 25, 'Finnair'],
 [2017, 26, 'AirAsia'],
 [2017, 27, 'Cathay Dragon'],
 [2017, 28, 'Norwegian'],
 [2017, 29, 'Air Canada'],
 [2017, 30, 'Aeroflot'],
 [2017, 31, 'Malaysia Airlines'],
 [2017, 32, 'Delta Air Lines'],
 [2017, 33, 'Virgin Atlantic'],
 [2017, 34, 'Korean Air'],
 [2017, 35, 'China Airlines'],
 [2017, 36, 'Alaska Airlines'],
 [2017, 37, 'Aegean Airlines'],
 [2017, 38, 'Aer Lingus'],
 [2017, 39, 'jetBlue Airways'],
 [2017, 40, 'British Airways'],
 [2017, 41, 'EasyJet'],
 [2017, 42, 'Iberia'],
 [2017, 43, 'Virgin America'],
 [2017, 44, 'Jetstar Airways'],
 [2017, 45, 'AirAsia X'],
 [2017, 46, 'Air Astana'],
 [2017, 47, 'Vietnam Airlines'],
 [2017, 48, 'Ethiopian Airlines'],
 [2017, 49, 'South African Airways'],
 [2017, 50, 'Avianca'],
 [2017, 51, 'Saudia'],
 [2017, 52, 'Azul Airlines'],
 [2017, 53, 'Oman Air'],
 [2017, 54, 'Southwest Airlines'],
 [2017, 55, 'Porter Airlines'],
 [2017, 56, 'SilkAir'],
 [2017, 57, 'IndiGo'],
 [2017, 58, 'WestJet'],
 [2017, 59, 'LATAM'],
 [2017, 60, 'Scoot'],
 [2017, 61, 'Jetstar Asia'],
 [2017, 62, 'TAP Portugal'],
 [2017, 63, 'Alitalia'],
 [2017, 64, 'Eurowings'],
 [2017, 65, 'SAS Scandinavian'],
 [2017, 66, 'Thomson Airways'],
 [2017, 67, 'Philippine Airlines'],
 [2017, 68, 'Brussels Airlines'],
 [2017, 69, 'Copa Airlines'],
 [2017, 70, 'Air Transat'],
 [2017, 71, 'Azerbaijan Airlines'],
 [2017, 72, 'China Eastern Airlines'],
 [2017, 73, 'Jet Airways'],
 [2017, 74, 'American Airlines'],
 [2017, 75, 'Fiji Airways'],
 [2017, 76, 'Ryanair'],
 [2017, 77, 'Air Mauritius'],
 [2017, 78, 'United Airlines'],
 [2017, 79, 'LOT Polish'],
 [2017, 80, 'Air Seychelles'],
 [2017, 81, 'SriLankan Airlines'],
 [2017, 82, 'Icelandair'],
 [2017, 83, 'Juneyao Air'],
 [2017, 84, 'Gulf Air'],
 [2017, 85, 'Air Berlin'],
 [2017, 86, 'Hawaiian Airlines'],
 [2017, 87, 'American Eagle'],
 [2017, 88, 'Vueling Airlines'],
 [2017, 89, 'Air Nostrum'],
 [2017, 90, 'Tigerair'],
 [2017, 91, 'Kenya Airways'],
 [2017, 92, 'Royal Brunei Airlines'],
 [2017, 93, 'Air Malta'],
 [2017, 94, 'Xiamen Airlines'],
 [2017, 95, 'S7 Airlines'],
 [2017, 96, 'Peach'],
 [2017, 97, 'Royal Air Maroc'],
 [2017, 98, 'Air China'],
 [2017, 99, 'Air Canada rouge'],
 [2017, 100, 'Aeromexico'],
 [2018, 1, 'Singapore Airlines'],
 [2018, 2, 'Qatar Airways'],
 [2018, 3, 'ANA All Nippon Airways'],
 [2018, 4, 'Emirates'],
 [2018, 5, 'EVA Air'],
 [2018, 6, 'Cathay Pacific Airways'],
 [2018, 7, 'Lufthansa'],
 [2018, 8, 'Hainan Airlines'],
 [2018, 9, 'Garuda Indonesia'],
 [2018, 10, 'Thai Airways'],
 [2018, 11, 'Qantas Airways'],
 [2018, 12, 'Swiss International Air Lines'],
 [2018, 13, 'Japan Airlines'],
 [2018, 14, 'China Southern Airlines'],
 [2018, 15, 'Etihad Airways'],
 [2018, 16, 'Austrian Airlines'],
 [2018, 17, 'Air New Zealand'],
 [2018, 18, 'Turkish Airlines'],
 [2018, 19, 'KLM Royal Dutch Airlines'],
 [2018, 20, 'Hong Kong Airlines'],
 [2018, 21, 'Bangkok Airways'],
 [2018, 22, 'Virgin Australia'],
 [2018, 23, 'Aeroflot'],
 [2018, 24, 'Asiana Airlines'],
 [2018, 25, 'Air France'],
 [2018, 26, 'Cathay Dragon'],
 [2018, 27, 'Finnair'],
 [2018, 28, 'AirAsia'],
 [2018, 29, 'Virgin Atlantic'],
 [2018, 30, 'Air Canada'],
 [2018, 31, 'British Airways'],
 [2018, 32, 'Norwegian'],
 [2018, 33, 'Korean Air'],
 [2018, 34, 'Malaysia Airlines'],
 [2018, 35, 'China Airlines'],
 [2018, 36, 'Aer Lingus'],
 [2018, 37, 'Delta Air Lines'],
 [2018, 38, 'Alaska Airlines'],
 [2018, 39, 'Aegean Airlines'],
 [2018, 40, 'Ethiopian Airlines'],
 [2018, 41, 'Iberia'],
 [2018, 42, 'jetBlue Airways'],
 [2018, 43, 'EasyJet'],
 [2018, 44, 'Oman Air'],
 [2018, 45, 'South African Airways'],
 [2018, 46, 'Jetstar Airways'],
 [2018, 47, 'AirAsia X'],
 [2018, 48, 'Air Astana'],
 [2018, 49, 'Philippine Airlines'],
 [2018, 50, 'Vietnam Airlines'],
 [2018, 51, 'Avianca'],
 [2018, 52, 'Saudia'],
 [2018, 53, 'Azul Airlines'],
 [2018, 54, 'WestJet'],
 [2018, 55, 'IndiGo'],
 [2018, 56, 'SilkAir'],
 [2018, 57, 'Southwest Airlines'],
 [2018, 58, 'Azerbaijan Airlines'],
 [2018, 59, 'Eurowings'],
 [2018, 60, 'SAS Scandinavian'],
 [2018, 61, 'Scoot'],
 [2018, 62, 'Porter Airlines'],
 [2018, 63, 'LATAM'],
 [2018, 64, 'Ryanair'],
 [2018, 65, 'Fiji Airways'],

In [11]:
# IATA Designator code
iata = {
    'Qatar Airways': 'QR',
    'Asiana Airlines': 'OZ',
    'Singapore Airlines': 'SQ',
    'Cathay Pacific Airways': 'CX',
    'ANA All Nippon Airways': 'NH',
    'Etihad Airway': 'EY',
    'Turkish Airlines': 'TK',
    'Emirates': 'EK',
    'Thai Airways': 'TG',
    'Malaysia Airlines': 'MH',
    'Garuda Indonesia': 'GA',
    'Virgin Australia': 'VA',
    'EVA Air': 'BR',
    'Lufthansa': 'LH',
    'Qantas Airways': 'QF',
    'Korean Air': 'KE',
    'Air New Zealand': 'NZ',
    'Swiss International Air Lines': 'LX',
    'Air Canada': 'AC',
    'Hainan Airlines': 'HU',
    'Dragonair': 'KA',
    'AirAsia': 'AK',
    'Oman Air': 'WY',
    'Aegean Airlines': 'A3',
    'South African Airways': 'SA',
    'Virgin America': 'VX',
    'Bangkok Airways': 'PG',
    'British Airways': 'BA',
    'China Southern Airlines': 'CZ',
    'Jetstar Airways': 'JQ',
    'Finnair': 'AY',
    'TAM Airlines': 'JJ',
    'China Airlines': 'CI',
    'KLM Royal Dutch Airlines': 'KL',
    'Japan Airlines': 'JL',
    'SilkAir': 'MI',
    'Air China': 'CA',
    'LAN Airlines': 'LA',
    'Austrian Airlines': 'OS',
    'AirAsia X': 'D7',
    'EasyJet': 'U2',
    'TACA Airlines': 'TA',
    'WestJet': 'WS',
    'China Eastern Airlines': 'MU',
    'Hong Kong Airlines': 'HX',
    'Jetstar Asia': '3K',
    'Vietnam Airlines': 'VN',
    'Air France': 'AF',
    'Alaska Airlines': 'AS',
    'Virgin Atlantic': 'VS',
    'Southwest Airlines': 'WN',
    'jetBlue Airways': 'B6',
    'Air Astana': 'KC',
    'Azul Airlines': 'AD',
    'IndiGo': '6E',
    'Avianca': 'AV',
    'Delta Air Lines': 'DL',
    'Jet Airways': 'QJ',
    'bmi British Midland': 'BD',
    'American Eagle': 'MQ',
    'Copa Airlines': 'CM',
    'Air Nostrum': 'YW',
    'Brussels Airlines': 'SN',
    'United Airlines': 'UA',
    'Air Berlin': 'AB',
    'Kulula': 'MN',
    'TAP Portugal': 'TP',
    'SAS Scandinavian': 'SK',
    'TRIP Airlines': '',
    'SriLankan Airlines': 'UL',
    'Air Mauritius': 'MK',
    'Transaero Airlines': 'UN',
    'Baboo Airlines': 'QH',
    'Norwegian': 'DY',
    'NIKI': 'HG',
    'Air Transat': 'TS',
    'Hong Kong Express': 'UO',
    'Kenya Airways': 'KQ',
    'Kingfisher Airlines': 'IT',
    'Hawaiian Airlines': 'HA',
    'SpiceJet': 'SG',
    'Gulf Air': 'GF',
    'Alitalia': 'AZ',
    'American Airlines': 'AA',
    'Aeroflot': 'SU',
    'Tigerair': 'TR',
    'Saudia': 'SV',
    'Icelandair': 'FI',
    'Shenzhen Airlines': 'ZH',
    'Porter Airlines': 'P3',
    'Aer Arann': 'RE',
    'Tianjin Airlines': 'GS',
    'Nok Air': 'DD',
    'Royal Jordanian Airlines': 'RJ',
    'Egyptair': 'MS',
    'Air Pacific': 'FJ',
    'Aer Lingus': 'EI',
    'Aer Busan': 'BX',
    'Cyprus Airways': 'CY',
    'Skymark Airlines': 'BC',
    'Air Seychelles': 'HM',
    'Azerbaijan Airlines': 'J2',
    'Scoot': 'TR',
    'Thomson Airways': 'BY',
    'Ethiopian Airlines': 'ET',
    'Peach': 'MM',
    'Philippine Airlines': 'PR',
    'Germanwings': '4U',
    'Iberia': 'IB',
    'S7 Airlines': 'S7',
    'US Airways': 'US',
    'Vueling Airlines': 'VY',
    'TAAG Angola Airlines': 'DT',
    'Mango': 'JE',
    'Fiji Airways': 'FJ',
    'Croatia Airlines': 'OU',
    'Juneyao Air': 'HO',
    'Eurowings': 'EW',
    'LOT Polish': 'LO',
    'Aeromexico': 'AM',
    'Royal Brunei Airlines': 'BI',
    'Cathay Dragon': 'KA',
    'LATAM': 'LA',
    'Ryanair': 'FR',
    'Air Malta': 'KM',
    'Xiamen Airlines': 'MF',
    'Royal Air Maroc': 'AT',
    'Air Canada rouge': 'AC',
    'TUI Airways': 'X3*',
    'Air Dolomiti': 'EN',
    'Vistara': 'UK',
    'Jet2.com': 'LS',
    'PAL Express': '2P',
    'AtlasGlobal': 'KK',
    'LEVEL': 'LV',
    'Flynas': 'XY',
    'JetBlue Airways': 'B6',
    'Bamboo Airways': 'QH',
    'JetSmart': 'JA',
    'Spring Airlines': 'IJ',
    'StarFlyer': '7G',
    'Air Arabia': 'G9',
    'Wizz Air': 'W6',
    'STARLUX Airlines': 'JX',
    'Citilink': 'QG',
    'SunExpress': 'XQ',
    'airBaltic': 'BT',
    'Rex Airlines': 'ZL',
    'Kuwait Airways': 'KU',
    'flyDubai': 'FZ',
    'Sky Airline': 'H2',
    'Air Serbia': 'JU',
    'ITA Airways': 'AZ',
    'Buta Airways': 'J2',
    'Azul Brazilian': 'AD',
    'Volotea': 'V7',
    'Transavia France': 'TO',
    'Sun Country Airlines': 'SY',
    'JetSMART Airlines': 'JA',
    'SKY Airline': 'H2',
    'RwandAir': 'WB',
    'PLAY': 'OG',
    'Breeze Airways': 'MX',
    'Iberia Express': 'I2',
    'Allegiant Air': 'G4',
    'Air India': 'AI',
    'FlyArystan': 'KC',
    'Etihad Airways': 'EY'
}

In [13]:
columns = ["Year", "Rank", "Airline"]

In [15]:
df = pd.DataFrame(all_data, columns=columns)

In [16]:
df['UniqueCarrier'] = df['Airline'].map(iata)

In [17]:
df.replace("", np.nan, inplace=True)

In [18]:
df

      Year  Rank                 Airline UniqueCarrier
0     2012     1           Qatar Airways            QR
1     2012     2         Asiana Airlines            OZ
2     2012     3      Singapore Airlines            SQ
3     2012     4  Cathay Pacific Airways            CX
4     2012     5  ANA All Nippon Airways            NH
...    ...   ...                     ...           ...
1195  2024    96     Philippine Airlines            PR
1196  2024    97           Copa Airlines            CM
1197  2024    98            Air Dolomiti            EN
1198  2024    99       Hawaiian Airlines            HA
1199  2024   100              FlyArystan            KC

[1200 rows x 4 columns]

In [20]:
df[df.isna().any(axis=1)]

    Year  Rank        Airline UniqueCarrier
68  2012    69  TRIP Airlines           NaN